"""ParaView 3D CFD visualization workflow for pulmonary models."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Literal

from svztagent.config.load import detect_workspace_root, load_workspace_config, resolve_cluster
from svztagent.config.models import ParaViewVizConfig, PatientParaViewVizOverride
from svztagent.core.errors import ConfigError
from svztagent.core.manifest import (
    read_manifest,
    record_paraview_viz_submission,
    write_manifest,
)
from svztagent.core.paths import (
    build_iteration_local_paths,
    build_local_run_paths,
    iteration_dir_name,
    validate_run_id,
)
from svztagent.hpc.interfaces import (
    ExecutionMode,
    FileTransferAdapter,
    RemoteExecAdapter,
    SchedulerAdapter,
    SyncDirection,
)
from svztagent.hpc.slurm import SlurmSchedulerAdapter, SlurmSubmitOptions
from svztagent.workflows.tune_trees import _build_default_adapters


# ---------------------------------------------------------------------------
# pvpython script template
# ---------------------------------------------------------------------------

_PVPYTHON_CONFIG_HEADER = """\
# Auto-generated by svzt-agent paraview_viz workflow. Do not edit.
SIMULATION_DIR = {simulation_dir!r}
OUTPUT_DIR = {output_dir!r}
CYCLE_DURATION_S = {cycle_duration_s!r}
DT = {dt!r}
IMAGE_RESOLUTION = {image_resolution!r}
CAMERA_OFFSET_DIR = {camera_offset_dir!r}
CAMERA_VIEW_UP = {camera_view_up!r}
PRESSURE_FIELD = {pressure_field!r}
VELOCITY_FIELD = {velocity_field!r}
WSS_FIELD = {wss_field!r}
DISPLACEMENT_FIELD = {displacement_field!r}
"""

# Raw string so curly braces inside f-strings evaluate at pvpython runtime.
# Uses ''' delimiter so inner """ docstrings are safe.
_PVPYTHON_SCRIPT_BODY = r'''
import re
import sys
import json
from pathlib import Path

import numpy as np
import vtk
from vtk.util.numpy_support import vtk_to_numpy, numpy_to_vtk

# Unit conversion: CFD pressure (dyn/cm²) → clinical display units (mmHg)
PRESSURE_TO_MMHG = 1.0 / 1333.22
SCALAR_BAR_POSITION = [0.885, 0.2]
SCALAR_BAR_LENGTH = 0.66
SCALAR_BAR_THICKNESS = 32
SCALAR_BAR_TITLE_FONT_SIZE = 16
SCALAR_BAR_LABEL_FONT_SIZE = 14
SCALAR_BAR_TEXT_COLOR = [0.0, 0.0, 0.0]


def _extract_step(path):
    m = re.search(r"result_(\d+)\.vtu$", Path(path).name)
    return int(m.group(1)) if m else -1


def _find_vtu_files(sim_dir):
    sim_path = Path(sim_dir)
    files = sorted(sim_path.glob("*-procs/result_*.vtu"), key=_extract_step)
    if not files:
        files = sorted(sim_path.glob("result_*.vtu"), key=_extract_step)
    if not files:
        raise FileNotFoundError(f"No result_*.vtu files found in {sim_dir}")
    return files


def _last_cycle_files(all_files, cycle_duration_s, dt):
    """Return files whose simulation time falls within the last cardiac cycle.

    VTU files are output every N timesteps so index-based slicing is wrong —
    we filter by actual simulation time derived from each file's step number.
    """
    last_step = _extract_step(all_files[-1])
    last_time = last_step * dt
    cycle_start_time = last_time - cycle_duration_s
    # Keep files whose step number implies time >= cycle_start_time
    cycle_start_step = cycle_start_time / dt
    result = [f for f in all_files if _extract_step(f) >= cycle_start_step]
    return result if result else all_files


def _read_vtu(path):
    reader = vtk.vtkXMLUnstructuredGridReader()
    reader.SetFileName(str(path))
    reader.Update()
    mesh = vtk.vtkUnstructuredGrid()
    mesh.DeepCopy(reader.GetOutput())
    return mesh


def _point_array(mesh, *names):
    pd = mesh.GetPointData()
    for name in names:
        arr = pd.GetArray(name)
        if arr is not None:
            return arr, name
    return None, None


def _systolic_frame(files):
    """Return file with highest mean pressure in the last cardiac cycle."""
    best_path, best_p = files[0], -float("inf")
    for f in files:
        mesh = _read_vtu(f)
        arr, _ = _point_array(mesh, PRESSURE_FIELD)
        if arr is None:
            continue
        vals = vtk_to_numpy(arr)
        mean_p = float(np.mean(vals[:, 0] if vals.ndim == 2 else vals))
        if mean_p > best_p:
            best_p, best_path = mean_p, f
    return best_path


def _build_cycle_averages(files, tmp_path):
    """One sequential pass over last-cycle frames computing all cycle-averaged fields
    and global scalar ranges needed for consistent animation coloring.

    Computes and writes to tmp_path:
      MeanPressure  — cycle-averaged pressure scalar
      MeanVelocity  — cycle-averaged velocity magnitude
      TAWSS         — time-averaged WSS magnitude

    Returns a dict:
      {
        "fields": set of field names written to tmp_path,
        "scalar_ranges": {
            PRESSURE_FIELD: [global_min, global_max],  # for animation LUT
            VELOCITY_FIELD: [global_min, global_max],
        }
      }
    """
    acc_p = acc_v = acc_w = None
    n_p = n_v = n_w = 0
    ref = None
    p_min = p_max = v_min = v_max = None

    for f in files:
        mesh = _read_vtu(f)
        ref = mesh  # keep last successfully-read mesh as geometry carrier

        # Pressure (scalar)
        arr, _ = _point_array(mesh, PRESSURE_FIELD)
        if arr is not None:
            vals = vtk_to_numpy(arr)
            p = (vals[:, 0] if vals.ndim == 2 else vals).astype(np.float64)
            acc_p = p.copy() if acc_p is None else acc_p + p
            lo, hi = float(p.min()), float(p.max())
            p_min = lo if p_min is None else min(p_min, lo)
            p_max = hi if p_max is None else max(p_max, hi)
            n_p += 1

        # Velocity magnitude
        arr, _ = _point_array(mesh, VELOCITY_FIELD)
        if arr is not None:
            vals = vtk_to_numpy(arr)
            mag = (np.linalg.norm(vals, axis=1) if vals.ndim == 2 else np.abs(vals)).astype(np.float64)
            acc_v = mag.copy() if acc_v is None else acc_v + mag
            lo, hi = float(mag.min()), float(mag.max())
            v_min = lo if v_min is None else min(v_min, lo)
            v_max = hi if v_max is None else max(v_max, hi)
            n_v += 1

        # WSS magnitude (→ TAWSS)
        arr, _ = _point_array(mesh, WSS_FIELD, "vWSS")
        if arr is not None:
            vals = vtk_to_numpy(arr)
            mag = (np.linalg.norm(vals, axis=1) if vals.ndim == 2 else np.abs(vals)).astype(np.float64)
            acc_w = mag.copy() if acc_w is None else acc_w + mag
            n_w += 1

    if ref is None:
        return {"fields": set(), "scalar_ranges": {}}

    pd = ref.GetPointData()
    available = set()

    def _add(name, acc, n, scale=1.0):
        if n > 0:
            a = numpy_to_vtk((acc / n * scale).astype(np.float64), deep=True)
            a.SetName(name)
            pd.AddArray(a)
            available.add(name)

    _add("MeanPressure",  acc_p, n_p, scale=PRESSURE_TO_MMHG)  # stored in mmHg
    _add("MeanVelocity",  acc_v, n_v)
    _add("TAWSS",         acc_w, n_w)

    writer = vtk.vtkXMLUnstructuredGridWriter()
    writer.SetFileName(str(tmp_path))
    writer.SetInputData(ref)
    writer.Write()

    scalar_ranges = {}
    if p_min is not None:
        # Convert pressure range to mmHg for consistent animation LUT
        scalar_ranges[PRESSURE_FIELD] = [p_min * PRESSURE_TO_MMHG, p_max * PRESSURE_TO_MMHG]
    if v_min is not None:
        scalar_ranges[VELOCITY_FIELD] = [v_min, v_max]
    return {"fields": available, "scalar_ranges": scalar_ranges}


def _norm3(v):
    a = np.asarray(v, dtype=float)
    n = np.linalg.norm(a)
    return (a / n).tolist() if n > 1e-12 else [0.0, -1.0, 0.0]


def _setup_camera(view, bounds):
    import math
    cx = 0.5 * (bounds[0] + bounds[1])
    cy = 0.5 * (bounds[2] + bounds[3])
    cz = 0.5 * (bounds[4] + bounds[5])
    dx = bounds[1] - bounds[0]
    dy = bounds[3] - bounds[2]
    dz = bounds[5] - bounds[4]
    diag = math.sqrt(dx*dx + dy*dy + dz*dz) or 1.0
    # Camera distance: model diagonal fills ~80% of the vertical FOV (30°).
    # dist = diag / (2 * tan(15°) * 0.8) ≈ diag * 2.33
    # Do NOT call ResetCamera() — it resets to defaults when no geometry is shown yet.
    dist = diag * 2.33
    d = _norm3(CAMERA_OFFSET_DIR)
    view.CameraFocalPoint = [cx, cy, cz]
    view.CameraPosition = [cx + d[0] * dist, cy + d[1] * dist, cz + d[2] * dist]
    if CAMERA_VIEW_UP is not None:
        # Explicit view-up from config (read from ParaView GUI Python Shell).
        view.CameraViewUp = list(CAMERA_VIEW_UP)
    else:
        # Auto-select: Z-up unless camera is nearly vertical, then Y-up.
        view.CameraViewUp = [0.0, 0.0, 1.0] if abs(d[2]) < 0.9 else [0.0, 1.0, 0.0]
    print(f"[pviz] Camera: focal={[round(v,1) for v in [cx,cy,cz]]} "
          f"dist={dist:.1f} dir={[round(v,3) for v in d]}")


def _has_point_array(source, name):
    """Return True if the source pipeline output has a point data array with the given name."""
    info = source.GetDataInformation().GetPointDataInformation()
    for i in range(info.GetNumberOfArrays()):
        if info.GetArrayInformation(i).GetName() == name:
            return True
    return False


def _lut_scalar_range(lut):
    """Return the scalar range encoded in a ParaView color transfer function."""
    pts = list(getattr(lut, "RGBPoints", []) or [])
    if len(pts) >= 5:
        return [float(pts[0]), float(pts[-4])]
    return None


def _style_scalar_bar(scalar_bar, title):
    """Apply the locked pulmonary postprocessing scalar-bar style."""
    scalar_bar.Visibility = 1
    scalar_bar.Title = title
    scalar_bar.ComponentTitle = ""
    scalar_bar.TitleFontSize = SCALAR_BAR_TITLE_FONT_SIZE
    scalar_bar.LabelFontSize = SCALAR_BAR_LABEL_FONT_SIZE
    scalar_bar.TitleColor = SCALAR_BAR_TEXT_COLOR
    scalar_bar.LabelColor = SCALAR_BAR_TEXT_COLOR
    scalar_bar.WindowLocation = "Any Location"
    scalar_bar.Orientation = "Vertical"
    scalar_bar.Position = SCALAR_BAR_POSITION
    scalar_bar.ScalarBarLength = SCALAR_BAR_LENGTH
    scalar_bar.ScalarBarThickness = SCALAR_BAR_THICKNESS


def _style_render_view(view):
    """Apply the locked pulmonary postprocessing view style."""
    view.Background = [1.0, 1.0, 1.0]
    view.OrientationAxesVisibility = 0
    view.CenterAxesVisibility = 0


def _style_volume_opacity(field, lut, scalar_range=None):
    """Use a linear min-transparent to max-opaque ramp for volume rendering."""
    from paraview.simple import GetOpacityTransferFunction

    sr = scalar_range or _lut_scalar_range(lut)
    if not sr:
        return
    otf = GetOpacityTransferFunction(field)
    otf.Points = [sr[0], 0.0, 0.5, 0.0, sr[1], 1.0, 0.5, 0.0]


def _warp_by_displacement(source):
    """Apply WarpByVector using DISPLACEMENT_FIELD.

    Returns the warped pipeline object, or the original source if the
    displacement field is absent (with a warning).
    """
    from paraview.simple import WarpByVector
    if not _has_point_array(source, DISPLACEMENT_FIELD):
        print(f"[pviz] WARNING: '{DISPLACEMENT_FIELD}' not found — skipping displacement warp")
        return source
    w = WarpByVector(Input=source)
    w.Vectors = ["POINTS", DISPLACEMENT_FIELD]
    w.ScaleFactor = 1.0
    print(f"[pviz] Warping geometry by '{DISPLACEMENT_FIELD}'")
    return w


def _render_field(source, field, view, out_path, cmap, label, representation="Surface"):
    """Render a single field to a PNG.

    representation: "Surface" (extract outer shell, good for pressure/WSS)
                    "Volume"  (ray-cast through the 3-D mesh, good for velocity)
    """
    from paraview.simple import (
        ColorBy,
        Delete,
        ExtractSurface,
        GetColorTransferFunction,
        GetScalarBar,
        Hide,
        SaveScreenshot,
        Show,
    )

    surf = None
    if representation == "Surface":
        surf = ExtractSurface(Input=source)
        render_obj = Show(surf, view)
    else:
        render_obj = Show(source, view)

    render_obj.Representation = representation
    ColorBy(render_obj, ("POINTS", field))
    render_obj.RescaleTransferFunctionToDataRange(False, False)
    lut = GetColorTransferFunction(field)
    lut.ApplyPreset(cmap, True)

    if representation == "Volume":
        # Keep internal flow structure visible without obscuring the vessel wall.
        _style_volume_opacity(field, lut)

    sb = GetScalarBar(lut, view)
    _style_scalar_bar(sb, label)
    view.Update()
    SaveScreenshot(str(out_path), view, TransparentBackground=1)

    if surf is not None:
        Hide(surf, view)
        Delete(surf)
    else:
        Hide(source, view)
    return str(out_path)


def _render_animation_pass(cycle_files, view, field, cmap, label, scalar_range, frames_dir, prefix,
                            representation="Surface", calc_expr=None, calc_result=None):
    """Render each last-cycle VTU frame for one field and return list of PNG paths.

    Builds a persistent pipeline (reader → warp → [calculator] → [extract surface])
    and updates only the reader filename per frame for efficiency.

    representation: "Surface" or "Volume"
    calc_expr:      optional ParaView Calculator expression applied after warp
                    (e.g. 'Pressure / 1333.22' for mmHg, or 'mag(Velocity)' for magnitude)
    calc_result:    result array name written by the calculator
    """
    from paraview.simple import (
        Calculator, ColorBy, Delete, ExtractSurface, GetColorTransferFunction,
        GetOpacityTransferFunction, GetScalarBar, Hide, SaveScreenshot, Show,
        XMLUnstructuredGridReader,
    )

    if not cycle_files:
        return []

    Path(frames_dir).mkdir(parents=True, exist_ok=True)

    # --- Build persistent pipeline ---
    reader = XMLUnstructuredGridReader(FileName=[str(cycle_files[0])])
    reader.UpdatePipeline()

    # Warp by displacement (CMM simulations keep the displacement field in each VTU)
    warped = _warp_by_displacement(reader)

    # Optional field transformation (unit conversion or vector → scalar magnitude)
    if calc_expr and calc_result:
        calc = Calculator(Input=warped)
        calc.Function = calc_expr
        calc.ResultArrayName = calc_result
        pipeline_end = calc
        render_field = calc_result
    else:
        pipeline_end = warped
        render_field = field

    # Surface vs. volume display
    if representation == "Surface":
        surf = ExtractSurface(Input=pipeline_end)
        disp_src = surf
    else:
        disp_src = pipeline_end
        surf = None

    disp = Show(disp_src, view)
    disp.Representation = representation
    ColorBy(disp, ("POINTS", render_field))

    lut = GetColorTransferFunction(render_field)
    lut.ApplyPreset(cmap, True)
    if scalar_range:
        lut.RescaleTransferFunction(scalar_range[0], scalar_range[1])
    else:
        disp.RescaleTransferFunctionToDataRange(False, False)

    if representation == "Volume":
        # Linear opacity ramp: transparent at min → opaque at max.
        _style_volume_opacity(render_field, lut, scalar_range)

    sb = GetScalarBar(lut, view)
    _style_scalar_bar(sb, label)

    frame_paths = []
    for i, vtu in enumerate(cycle_files):
        reader.FileName = [str(vtu)]
        reader.UpdatePipeline()
        view.Update()
        fp = Path(frames_dir) / f"{prefix}_{i:04d}.png"
        SaveScreenshot(str(fp), view, TransparentBackground=1)
        frame_paths.append(fp)
        if (i + 1) % 20 == 0 or (i + 1) == len(cycle_files):
            print(f"[pviz]   {prefix} animation: {i+1}/{len(cycle_files)} frames")

    Hide(disp_src, view)
    if surf is not None:
        Delete(surf)
    Delete(reader)
    return frame_paths


def _assemble_animation(frame_paths, prefix, out_dir, fps=20):
    """Combine PNG frames into an MP4 (ffmpeg) or GIF (imageio) animation.

    Falls back gracefully if neither tool is available, leaving the PNG frames
    in place and printing the manual ffmpeg command.

    Returns the path of the assembled file, or the frames directory on fallback.
    """
    import subprocess

    if not frame_paths:
        return None

    frames_dir = frame_paths[0].parent
    # ffmpeg printf-style input pattern (frames are 0-indexed, zero-padded to 4 digits)
    frame_pattern = str(frames_dir / f"{prefix}_%04d.png")
    mp4_path = Path(out_dir) / f"{prefix}_animation.mp4"

    try:
        result = subprocess.run(
            ["ffmpeg", "-y",
             "-framerate", str(fps),
             "-i", frame_pattern,
             "-c:v", "mpeg4", "-pix_fmt", "yuv420p", "-q:v", "5",
             str(mp4_path)],
            capture_output=True, timeout=300,
        )
        if result.returncode == 0:
            print(f"[pviz] Animation (MP4): {mp4_path}")
            return str(mp4_path)
        print(f"[pviz] ffmpeg error: {result.stderr.decode()[:300]}", file=sys.stderr)
    except FileNotFoundError:
        print(f"[pviz] ffmpeg not found — trying imageio GIF")
    except Exception as exc:
        print(f"[pviz] ffmpeg failed: {exc}", file=sys.stderr)

    # Fallback: animated GIF via imageio
    gif_path = Path(out_dir) / f"{prefix}_animation.gif"
    try:
        import imageio
        with imageio.get_writer(str(gif_path), mode="I", fps=fps, loop=0) as writer:
            for fp in frame_paths:
                writer.append_data(imageio.imread(str(fp)))
        print(f"[pviz] Animation (GIF): {gif_path}")
        return str(gif_path)
    except ImportError:
        pass
    except Exception as exc:
        print(f"[pviz] imageio GIF failed: {exc}", file=sys.stderr)

    # Last resort: leave frames and print manual command
    manual_cmd = f"ffmpeg -framerate {fps} -i {frame_pattern} -c:v mpeg4 -pix_fmt yuv420p -q:v 5 {mp4_path}"
    print(f"[pviz] Frames saved to: {frames_dir}")
    print(f"[pviz] Assemble manually: {manual_cmd}")
    return str(frames_dir)


def main():
    from paraview.simple import Calculator, CreateView, SetActiveView, XMLUnstructuredGridReader

    out = Path(OUTPUT_DIR)
    out.mkdir(parents=True, exist_ok=True)

    print(f"[pviz] Simulation dir: {SIMULATION_DIR}")
    all_files = _find_vtu_files(SIMULATION_DIR)
    print(f"[pviz] {len(all_files)} VTU files found")

    cycle = _last_cycle_files(all_files, CYCLE_DURATION_S, DT)
    print(f"[pviz] Last-cycle frames: {len(cycle)}")

    systolic = _systolic_frame(cycle)
    print(f"[pviz] Systolic frame: {systolic.name}")

    # One pass over all cycle frames: compute MeanPressure (mmHg), MeanVelocity, TAWSS
    # and collect global scalar ranges for consistent animation coloring.
    tmp_avg = out / "_tmp_cycle_avg.vtu"
    avg_result = _build_cycle_averages(cycle, tmp_avg)
    avg_fields = avg_result["fields"]
    scalar_ranges = avg_result["scalar_ranges"]
    if avg_fields:
        print(f"[pviz] Cycle averages computed from {len(cycle)} frames: {sorted(avg_fields)}")
    else:
        print("[pviz] WARNING: could not compute cycle averages — no VTU data read")

    view = CreateView("RenderView")
    view.ViewSize = IMAGE_RESOLUTION
    _style_render_view(view)
    SetActiveView(view)

    # ---- Systolic frame pipeline: reader → warp → derived fields ----
    systolic_reader = XMLUnstructuredGridReader(FileName=[str(systolic)])
    systolic_reader.UpdatePipeline()
    # Use reader bounds for camera — warp displacement is sub-mm and negligible
    # for camera positioning; GetDataInformation() on WarpByVector returns zeros
    # until the pipeline is explicitly rendered.
    bounds = systolic_reader.GetDataInformation().GetBounds()
    _setup_camera(view, bounds)
    systolic_warped = _warp_by_displacement(systolic_reader)

    # Systolic pressure → convert to mmHg for display
    systolic_p_mmhg = Calculator(Input=systolic_warped)
    systolic_p_mmhg.Function = f"{PRESSURE_FIELD} / 1333.22"
    systolic_p_mmhg.ResultArrayName = "Pressure_mmHg"

    # Systolic velocity → compute magnitude for volume rendering
    systolic_v_mag = Calculator(Input=systolic_warped)
    systolic_v_mag.Function = f"mag({VELOCITY_FIELD})"
    systolic_v_mag.ResultArrayName = "VelocityMagnitude"

    # ---- Averaged fields pipeline: reader → warp ----
    # MeanPressure is already in mmHg (scaled in _build_cycle_averages).
    # MeanVelocity is already a scalar magnitude.
    avg_reader = None
    avg_warped = None
    if avg_fields:
        avg_reader = XMLUnstructuredGridReader(FileName=[str(tmp_avg)])
        avg_reader.UpdatePipeline()
        avg_warped = _warp_by_displacement(avg_reader)

    outputs = {"systolic_frame": str(systolic)}

    # Render order: mean pressure, mean velocity, systolic pressure,
    #               systolic velocity, TAWSS.
    # Tuple: (source, field, filename, colormap, label, representation)
    renders = []
    if avg_warped and "MeanPressure" in avg_fields:
        renders.append((avg_warped,       "MeanPressure",    "mean_pressure.png",
                        "Cool to Warm",        "Mean Pressure (mmHg)",         "Surface"))
    if avg_warped and "MeanVelocity" in avg_fields:
        renders.append((avg_warped,       "MeanVelocity",    "mean_velocity_magnitude.png",
                        "Plasma (matplotlib)", "Mean Velocity (cm/s)",         "Volume"))
    renders.append(    (systolic_p_mmhg,  "Pressure_mmHg",   "systolic_pressure.png",
                        "Cool to Warm",        "Systolic Pressure (mmHg)",     "Surface"))
    renders.append(    (systolic_v_mag,   "VelocityMagnitude","systolic_velocity_magnitude.png",
                        "Plasma (matplotlib)", "Systolic Velocity (cm/s)",     "Volume"))
    if avg_warped and "TAWSS" in avg_fields:
        renders.append((avg_warped,       "TAWSS",           "tawss.png",
                        "Plasma (matplotlib)", "TAWSS (dyn/cm²)",              "Surface"))

    for source, field, fname, cmap, label, representation in renders:
        try:
            p = _render_field(source, field, view, out / fname, cmap, label, representation)
            outputs[fname] = p
            print(f"[pviz] Saved: {p}")
        except Exception as exc:
            print(f"[pviz] WARNING: {fname} failed: {exc}", file=sys.stderr)

    if tmp_avg.exists():
        tmp_avg.unlink()

    # ---- Animations (pressure and velocity, one frame per last-cycle VTU) ----
    # Each animation pass builds its own reader→warp→calc pipeline for independence.
    print(f"[pviz] Rendering animations ({len(cycle)} frames each) ...")
    anim_frames_root = out / "animation_frames"
    for field, cmap, label, prefix, representation, calc_expr, calc_result in [
        (PRESSURE_FIELD, "Cool to Warm",        "Pressure (mmHg)", "pressure", "Surface",
         f"{PRESSURE_FIELD} / 1333.22", "Pressure_mmHg"),
        (VELOCITY_FIELD, "Plasma (matplotlib)", "Velocity (cm/s)", "velocity", "Volume",
         f"mag({VELOCITY_FIELD})", "VelocityMagnitude"),
    ]:
        frames = _render_animation_pass(
            cycle, view, field, cmap, label,
            scalar_ranges.get(field),
            anim_frames_root / prefix,
            prefix,
            representation=representation,
            calc_expr=calc_expr,
            calc_result=calc_result,
        )
        anim_path = _assemble_animation(frames, prefix, out, fps=20)
        if anim_path:
            outputs[f"{prefix}_animation"] = anim_path

    summary = out / "paraview_viz_summary.json"
    summary.write_text(json.dumps({"outputs": outputs}, indent=2), encoding="utf-8")
    print(f"[pviz] Done. Summary: {summary}")


main()
'''


# ---------------------------------------------------------------------------
# Script rendering
# ---------------------------------------------------------------------------


def _render_pvpython_script(
    *,
    simulation_dir: str,
    output_dir: str,
    cycle_duration_s: float,
    dt: float,
    image_resolution: list[int],
    camera_offset_dir: list[float],
    camera_view_up: list[float] | None,
    pressure_field: str,
    velocity_field: str,
    wss_field: str,
    displacement_field: str,
) -> str:
    header = _PVPYTHON_CONFIG_HEADER.format(
        simulation_dir=simulation_dir,
        output_dir=output_dir,
        cycle_duration_s=cycle_duration_s,
        dt=dt,
        image_resolution=image_resolution,
        camera_offset_dir=camera_offset_dir,
        camera_view_up=camera_view_up,
        pressure_field=pressure_field,
        velocity_field=velocity_field,
        wss_field=wss_field,
        displacement_field=displacement_field,
    )
    return header + _PVPYTHON_SCRIPT_BODY


def _render_slurm_script(
    *,
    pvpython_path: str,
    remote_pvpython_script: str,
    remote_root: str,
    remote_logs_dir: str,
    output_dir: str,
    account: str | None,
    partition: str | None,
    wall_time_hours: int | None,
    cpus_per_task: int | None,
    mem: str | None,
) -> str:
    header_lines = [
        f"#SBATCH --chdir={remote_root}",
        f"#SBATCH --output={remote_logs_dir}/slurm-%j.out",
        f"#SBATCH --error={remote_logs_dir}/%x_%j.error",
    ]
    if account:
        header_lines.append(f"#SBATCH --account={account}")
    if partition:
        header_lines.append(f"#SBATCH --partition={partition}")
    if wall_time_hours is not None:
        header_lines.append(f"#SBATCH --time={wall_time_hours}:00:00")
    if cpus_per_task is not None:
        header_lines.append(f"#SBATCH --cpus-per-task={cpus_per_task}")
    if mem is not None:
        header_lines.append(f"#SBATCH --mem={mem}")
    slurm_header = "\n".join(header_lines)
    summary_json = str(PurePosixPath(output_dir) / "paraview_viz_summary.json")

    anim_frames_root = str(PurePosixPath(output_dir) / "animation_frames")

    return f"""#!/usr/bin/env bash
{slurm_header}
set -euo pipefail

mkdir -p {json.dumps(output_dir)}

# Load ffmpeg for animation assembly (MP4 output).
module load ffmpeg 2>/dev/null || true

# Prevent Sherlock's system Python 3.12 packages from shadowing pvpython's
# bundled Python 3.10 (binary-incompatible → segfault on numpy/vtk import).
unset PYTHONPATH

# pvpython exits non-zero due to a benign ADIOS2 cleanup bug even on success.
# Check for the summary JSON to detect actual rendering failures.
set +e
{json.dumps(pvpython_path)} {json.dumps(remote_pvpython_script)}
PV_RC=$?
set -e
if [ ! -f {json.dumps(summary_json)} ]; then
    echo "ERROR: pvpython did not write summary JSON (exit code ${{PV_RC}})" >&2
    exit "${{PV_RC:-1}}"
fi
echo "ParaView visualization complete (pvpython exit code ${{PV_RC}})"

# Assemble animation frames into MP4s and GIFs using ffmpeg (runs in bash
# where the module is loaded, avoiding subprocess PATH issues inside pvpython).
ANIM_FPS=20
GIF_FPS=10
GIF_SCALE=960  # half horizontal resolution keeps GIF file sizes manageable
for FIELD in pressure velocity; do
    FRAME0="{anim_frames_root}/${{FIELD}}/${{FIELD}}_0000.png"
    MP4="{output_dir}/${{FIELD}}_animation.mp4"
    GIF="{output_dir}/${{FIELD}}_animation.gif"
    PALETTE="/tmp/${{FIELD}}_palette_${{SLURM_JOB_ID:-$$}}.png"
    if [ -f "${{FRAME0}}" ]; then
        echo "[anim] Assembling ${{FIELD}} MP4 ..."
        ffmpeg -y -loglevel warning \\
            -framerate ${{ANIM_FPS}} \\
            -i "{anim_frames_root}/${{FIELD}}/${{FIELD}}_%04d.png" \\
            -c:v mpeg4 -pix_fmt yuv420p -q:v 5 \\
            "${{MP4}}" && echo "[anim] Saved MP4: ${{MP4}}" || echo "[anim] ffmpeg MP4 failed for ${{FIELD}}" >&2

        # GIF: two-pass palette method for high-quality output.
        # Pass 1: extract an optimised 256-colour palette from the video.
        # Pass 2: dither frames with that palette.
        if [ -f "${{MP4}}" ]; then
            echo "[anim] Assembling ${{FIELD}} GIF ..."
            ffmpeg -y -loglevel warning -i "${{MP4}}" \\
                -vf "fps=${{GIF_FPS}},scale=${{GIF_SCALE}}:-1:flags=lanczos,palettegen=stats_mode=diff" \\
                "${{PALETTE}}" && \\
            ffmpeg -y -loglevel warning -i "${{MP4}}" -i "${{PALETTE}}" \\
                -lavfi "fps=${{GIF_FPS}},scale=${{GIF_SCALE}}:-1:flags=lanczos[x];[x][1:v]paletteuse=dither=bayer:bayer_scale=5:diff_mode=rectangle" \\
                "${{GIF}}" && echo "[anim] Saved GIF: ${{GIF}}" || echo "[anim] ffmpeg GIF failed for ${{FIELD}}" >&2
            rm -f "${{PALETTE}}"
        fi
    fi
done
"""


# ---------------------------------------------------------------------------
# Patient-specific config resolution
# ---------------------------------------------------------------------------


def _resolve_viz_config(
    base: ParaViewVizConfig,
    override: PatientParaViewVizOverride | None,
) -> ParaViewVizConfig:
    """Merge patient-level paraview_viz overrides on top of workspace defaults.

    Only fields explicitly set on the override (non-None) replace the base value.
    This means a patient only needs to specify camera_offset_dir / camera_view_up
    and inherits mem, wall_time_hours, image_resolution, field names from defaults.
    """
    if override is None:
        return base
    updates = override.model_dump(exclude_none=True)
    return base.model_copy(update=updates)


def _resolve_patient_viz_settings(config, manifest) -> tuple[ParaViewVizConfig, float, str | None]:
    patient_alias: str | None = manifest.patient.get("alias") if manifest.patient else None
    patient_cfg = None
    patient_override = None
    if patient_alias:
        patient_cfg = next((p for p in config.patients if p.alias == patient_alias), None)
        if patient_cfg is not None and patient_cfg.postprocess is not None:
            patient_override = patient_cfg.postprocess.paraview_viz
    viz_cfg = _resolve_viz_config(config.defaults.postprocess.paraview_viz, patient_override)

    threed_cfg = config.defaults.tuning.threed
    dt = threed_cfg.dt
    if patient_cfg is not None and patient_cfg.tuning is not None:
        if patient_cfg.tuning.threed is not None and patient_cfg.tuning.threed.dt is not None:
            dt = patient_cfg.tuning.threed.dt
    return viz_cfg, dt, patient_alias


# ---------------------------------------------------------------------------
# Local / remote path layouts
# ---------------------------------------------------------------------------


def _preop_local_paths(workspace_root: Path, run_id: str, iteration: int) -> dict[str, Path]:
    local_run = build_local_run_paths(workspace_root, run_id)
    iter_paths = build_iteration_local_paths(local_run, iteration)
    root = iter_paths["root"] / "paraview_viz"
    return {
        "root": root,
        "logs": root / "logs",
        "pvpython_script": root / "paraview_viz.py",
        "slurm_script": root / "run_paraview_viz.sh",
    }


def _preop_remote_paths(remote_run_dir: str, iteration: int) -> dict[str, str]:
    iter_dir = str(PurePosixPath(remote_run_dir) / "iterations" / iteration_dir_name(iteration))
    root = str(PurePosixPath(iter_dir) / "paraview_viz")
    return {
        "root": root,
        "logs": str(PurePosixPath(root) / "logs"),
        "pvpython_script": str(PurePosixPath(root) / "paraview_viz.py"),
        "slurm_script": str(PurePosixPath(root) / "run_paraview_viz.sh"),
        "output_dir": str(PurePosixPath(iter_dir) / "results" / "paraview_viz"),
        "simulation_dir": str(PurePosixPath(iter_dir) / "preop"),
    }


def _postop_local_paths(workspace_root: Path, run_id: str, source_iteration: int) -> dict[str, Path]:
    local_run = build_local_run_paths(workspace_root, run_id)
    root = (
        local_run.run_dir
        / "postop"
        / f"from-{iteration_dir_name(source_iteration)}"
        / "paraview_viz"
    )
    return {
        "root": root,
        "logs": root / "logs",
        "pvpython_script": root / "paraview_viz.py",
        "slurm_script": root / "run_paraview_viz.sh",
    }


def _postop_remote_paths(remote_postop_dir: str) -> dict[str, str]:
    root = str(PurePosixPath(remote_postop_dir) / "paraview_viz")
    return {
        "root": root,
        "logs": str(PurePosixPath(root) / "logs"),
        "pvpython_script": str(PurePosixPath(root) / "paraview_viz.py"),
        "slurm_script": str(PurePosixPath(root) / "run_paraview_viz.sh"),
        "output_dir": str(PurePosixPath(remote_postop_dir) / "results" / "paraview_viz"),
        "simulation_dir": str(PurePosixPath(remote_postop_dir) / "simulation"),
    }


def _adaptation_local_paths(
    workspace_root: Path,
    run_id: str,
    source_iteration: int,
    model_slug: str,
) -> dict[str, Path]:
    local_run = build_local_run_paths(workspace_root, run_id)
    root = (
        local_run.run_dir
        / "adaptation"
        / f"from-{iteration_dir_name(source_iteration)}"
        / model_slug
        / "paraview_viz"
    )
    return {
        "root": root,
        "logs": root / "logs",
        "pvpython_script": root / "paraview_viz.py",
        "slurm_script": root / "run_paraview_viz.sh",
    }


def _adaptation_remote_paths(remote_adaptation_dir: str) -> dict[str, str]:
    root = str(PurePosixPath(remote_adaptation_dir) / "paraview_viz")
    return {
        "root": root,
        "logs": str(PurePosixPath(root) / "logs"),
        "pvpython_script": str(PurePosixPath(root) / "paraview_viz.py"),
        "slurm_script": str(PurePosixPath(root) / "run_paraview_viz.sh"),
        "output_dir": str(PurePosixPath(remote_adaptation_dir) / "results" / "paraview_viz"),
        "simulation_dir": str(PurePosixPath(remote_adaptation_dir) / "simulation"),
    }


# ---------------------------------------------------------------------------
# Prepared / submitted job models
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class PreparedParaViewVizJob:
    run_id: str
    stage: str
    source_iteration: int
    local_root: Path
    local_logs_dir: Path
    local_pvpython_script: Path
    local_slurm_script: Path
    remote_root: str
    remote_logs_dir: str
    remote_pvpython_script: str
    remote_slurm_script: str
    remote_output_dir: str
    remote_simulation_dir: str
    remote_submission_metadata_path: str
    pvpython_script_content: str
    slurm_script_content: str
    submit_options: SlurmSubmitOptions


@dataclass(frozen=True)
class ParaViewVizSubmissionResult:
    run_id: str
    stage: str
    source_iteration: int
    remote_output_dir: str
    remote_slurm_script: str
    local_slurm_script: Path
    submitted_job_id: str
    command_previews: list[list[str]]


# ---------------------------------------------------------------------------
# Main submission entry point
# ---------------------------------------------------------------------------


def _prepare_paraview_viz_job(
    *,
    workspace_root: Path,
    run_id: str,
    manifest,
    cluster,
    source_iteration: int,
    stage: str,
    local_paths: dict[str, Path],
    remote_paths: dict[str, str],
    cycle_duration_s: float,
    job_name: str,
) -> PreparedParaViewVizJob:
    config = load_workspace_config(workspace_root)
    if cluster.executables.pvpython_path is None:
        raise ConfigError(
            "cluster executables.pvpython_path is required for ParaView visualization; "
            "set it in clusters.yaml"
        )

    viz_cfg, dt, _patient_alias = _resolve_patient_viz_settings(config, manifest)
    for key in ("root", "logs"):
        local_paths[key].mkdir(parents=True, exist_ok=True)

    pvpython_script = _render_pvpython_script(
        simulation_dir=remote_paths["simulation_dir"],
        output_dir=remote_paths["output_dir"],
        cycle_duration_s=cycle_duration_s,
        dt=dt,
        image_resolution=viz_cfg.image_resolution,
        camera_offset_dir=viz_cfg.camera_offset_dir,
        camera_view_up=viz_cfg.camera_view_up,
        pressure_field=viz_cfg.pressure_field,
        velocity_field=viz_cfg.velocity_field,
        wss_field=viz_cfg.wss_field,
        displacement_field=viz_cfg.displacement_field,
    )
    local_paths["pvpython_script"].write_text(pvpython_script, encoding="utf-8")

    slurm_script = _render_slurm_script(
        pvpython_path=cluster.executables.pvpython_path,
        remote_pvpython_script=remote_paths["pvpython_script"],
        remote_root=remote_paths["root"],
        remote_logs_dir=remote_paths["logs"],
        output_dir=remote_paths["output_dir"],
        account=config.defaults.scheduler.account,
        partition=config.defaults.scheduler.partition,
        wall_time_hours=viz_cfg.wall_time_hours,
        cpus_per_task=viz_cfg.cpus,
        mem=viz_cfg.mem,
    )
    local_paths["slurm_script"].write_text(slurm_script, encoding="utf-8")

    return PreparedParaViewVizJob(
        run_id=run_id,
        stage=stage,
        source_iteration=source_iteration,
        local_root=local_paths["root"],
        local_logs_dir=local_paths["logs"],
        local_pvpython_script=local_paths["pvpython_script"],
        local_slurm_script=local_paths["slurm_script"],
        remote_root=remote_paths["root"],
        remote_logs_dir=remote_paths["logs"],
        remote_pvpython_script=remote_paths["pvpython_script"],
        remote_slurm_script=remote_paths["slurm_script"],
        remote_output_dir=remote_paths["output_dir"],
        remote_simulation_dir=remote_paths["simulation_dir"],
        remote_submission_metadata_path=str(
            PurePosixPath(remote_paths["output_dir"]) / "paraview_viz_submission.json"
        ),
        pvpython_script_content=pvpython_script,
        slurm_script_content=slurm_script,
        submit_options=SlurmSubmitOptions(
            job_name=job_name,
            account=config.defaults.scheduler.account,
            partition=config.defaults.scheduler.partition,
            wall_time=f"{viz_cfg.wall_time_hours}:00:00",
            mem=viz_cfg.mem,
            cpus=str(viz_cfg.cpus),
        ),
    )


def _paraview_skip_reason(*, config, cluster, manifest) -> str | None:
    if cluster.executables.pvpython_path is None:
        return "pvpython_path_not_configured"
    viz_cfg, _dt, _patient_alias = _resolve_patient_viz_settings(config, manifest)
    if viz_cfg.cycle_duration_s is None:
        return "cycle_duration_s_not_configured"
    return None


def _prepare_preop_paraview_viz_job(
    *,
    workspace_root: Path,
    run_id: str,
    manifest,
    cluster,
    iteration: int,
    cycle_duration_s: float,
) -> PreparedParaViewVizJob:
    remote_run_dir = manifest.execution.remote_run_dir or manifest.remote.get("remote_run_dir")
    if not remote_run_dir:
        raise ConfigError(f"run '{run_id}' is missing remote_run_dir")
    return _prepare_paraview_viz_job(
        workspace_root=workspace_root,
        run_id=run_id,
        manifest=manifest,
        cluster=cluster,
        source_iteration=iteration,
        stage="preop",
        local_paths=_preop_local_paths(workspace_root, run_id, iteration),
        remote_paths=_preop_remote_paths(str(remote_run_dir), iteration),
        cycle_duration_s=cycle_duration_s,
        job_name=f"{run_id}-pviz",
    )


def _prepare_postop_paraview_viz_job(
    *,
    workspace_root: Path,
    run_id: str,
    manifest,
    cluster,
    remote_postop_dir: str | None = None,
    source_iteration: int | None = None,
) -> PreparedParaViewVizJob:
    postop_run = manifest.postop_run
    resolved_remote_postop_dir = remote_postop_dir
    resolved_source_iteration = source_iteration
    if resolved_remote_postop_dir is None or resolved_source_iteration is None:
        if not postop_run or not postop_run.remote_dir:
            raise ConfigError(
                f"run '{run_id}' has no postop_run recorded in manifest; submit the postop simulation first"
            )
        resolved_remote_postop_dir = postop_run.remote_dir
        resolved_source_iteration = int(postop_run.source_preop_iteration)
    config = load_workspace_config(workspace_root)
    viz_cfg, _dt, patient_alias = _resolve_patient_viz_settings(config, manifest)
    if viz_cfg.cycle_duration_s is None:
        alias_note = f" under patient {patient_alias!r}" if patient_alias else ""
        raise ConfigError(
            "ParaView visualization for postop requires postprocess.paraview_viz.cycle_duration_s"
            f"{alias_note}"
        )
    return _prepare_paraview_viz_job(
        workspace_root=workspace_root,
        run_id=run_id,
        manifest=manifest,
        cluster=cluster,
        source_iteration=int(resolved_source_iteration),
        stage="postop",
        local_paths=_postop_local_paths(workspace_root, run_id, int(resolved_source_iteration)),
        remote_paths=_postop_remote_paths(str(resolved_remote_postop_dir)),
        cycle_duration_s=viz_cfg.cycle_duration_s,
        job_name=f"{run_id}-pviz-post",
    )


def _prepare_adaptation_paraview_viz_job(
    *,
    workspace_root: Path,
    run_id: str,
    manifest,
    cluster,
    model: str,
    remote_adaptation_dir: str | None = None,
    source_iteration: int | None = None,
) -> PreparedParaViewVizJob:
    adaptation_run = None
    if remote_adaptation_dir is None or source_iteration is None:
        for record in reversed(manifest.adaptation_runs):
            if record.model.upper() == model.upper():
                adaptation_run = record
                break
        if adaptation_run is None:
            raise ConfigError(
                f"run '{run_id}' has no recorded adaptation run for model '{model.upper()}'"
            )
        remote_adaptation_dir = adaptation_run.remote_dir
        source_iteration = int(adaptation_run.source_preop_iteration)

    config = load_workspace_config(workspace_root)
    viz_cfg, _dt, patient_alias = _resolve_patient_viz_settings(config, manifest)
    if viz_cfg.cycle_duration_s is None:
        alias_note = f" under patient {patient_alias!r}" if patient_alias else ""
        raise ConfigError(
            "ParaView visualization for adaptation requires postprocess.paraview_viz.cycle_duration_s"
            f"{alias_note}"
        )
    model_slug = model.lower()
    return _prepare_paraview_viz_job(
        workspace_root=workspace_root,
        run_id=run_id,
        manifest=manifest,
        cluster=cluster,
        source_iteration=int(source_iteration),
        stage=f"adaptation-{model_slug}",
        local_paths=_adaptation_local_paths(workspace_root, run_id, int(source_iteration), model_slug),
        remote_paths=_adaptation_remote_paths(str(remote_adaptation_dir)),
        cycle_duration_s=viz_cfg.cycle_duration_s,
        job_name=f"{run_id}-pviz-adapt-{model_slug}",
    )


def _submit_prepared_paraview_viz_job(
    *,
    prepared: PreparedParaViewVizJob,
    manifest_path: Path,
    cluster,
    config,
    transfer_adapter: FileTransferAdapter | None,
    scheduler_adapter: SchedulerAdapter | None,
    remote_exec_adapter: RemoteExecAdapter | None,
    manifest_note: str,
) -> ParaViewVizSubmissionResult:
    if transfer_adapter is None or scheduler_adapter is None or remote_exec_adapter is None:
        default_transfer, default_scheduler, default_remote = _build_default_adapters(
            cluster=cluster,
            config=config,
            run_id=prepared.run_id,
            mode=ExecutionMode.EXECUTE,
        )
        transfer_adapter = transfer_adapter or default_transfer
        remote_exec_adapter = remote_exec_adapter or default_remote
        if scheduler_adapter is None:
            scheduler_adapter = SlurmSchedulerAdapter(
                remote_exec=remote_exec_adapter,
                runs_root=cluster.remote_roots.runs_root,
                submit_options=prepared.submit_options,
            )

    command_results = [
        transfer_adapter.ensure_remote_dir(prepared.remote_root),
        transfer_adapter.ensure_remote_dir(prepared.remote_logs_dir),
        transfer_adapter.ensure_remote_dir(prepared.remote_output_dir),
        transfer_adapter.push(str(prepared.local_pvpython_script), prepared.remote_pvpython_script),
        transfer_adapter.push(str(prepared.local_slurm_script), prepared.remote_slurm_script),
    ]
    submit_result = scheduler_adapter.submit(prepared.remote_slurm_script)
    command_results.append(submit_result.command)

    manifest = read_manifest(manifest_path)
    manifest = record_paraview_viz_submission(
        manifest,
        stage=prepared.stage,
        source_iteration=prepared.source_iteration,
        local_dir=str(prepared.local_root),
        remote_dir=prepared.remote_output_dir,
        local_script_path=str(prepared.local_slurm_script),
        remote_script_path=prepared.remote_slurm_script,
        scheduler_job_id=submit_result.job_id,
        note=manifest_note,
    )
    write_manifest(manifest, manifest_path)

    return ParaViewVizSubmissionResult(
        run_id=prepared.run_id,
        stage=prepared.stage,
        source_iteration=prepared.source_iteration,
        remote_output_dir=prepared.remote_output_dir,
        remote_slurm_script=prepared.remote_slurm_script,
        local_slurm_script=prepared.local_slurm_script,
        submitted_job_id=submit_result.job_id,
        command_previews=[result.argv for result in command_results],
    )


def submit_preop_paraview_viz(
    *,
    workspace_root: str | Path,
    run_id: str,
    iteration: int,
    cycle_duration_s: float,
    transfer_adapter: FileTransferAdapter | None = None,
    scheduler_adapter: SchedulerAdapter | None = None,
    remote_exec_adapter: RemoteExecAdapter | None = None,
) -> ParaViewVizSubmissionResult:
    root = detect_workspace_root(workspace_root)
    validated_run_id = validate_run_id(run_id)
    local_run = build_local_run_paths(root, validated_run_id)
    manifest = read_manifest(local_run.manifest)
    config = load_workspace_config(root)
    cluster = resolve_cluster(config, str(manifest.cluster.get("name")))
    prepared = _prepare_preop_paraview_viz_job(
        workspace_root=root,
        run_id=validated_run_id,
        manifest=manifest,
        cluster=cluster,
        iteration=iteration,
        cycle_duration_s=cycle_duration_s,
    )
    return _submit_prepared_paraview_viz_job(
        prepared=prepared,
        manifest_path=local_run.manifest,
        cluster=cluster,
        config=config,
        transfer_adapter=transfer_adapter,
        scheduler_adapter=scheduler_adapter,
        remote_exec_adapter=remote_exec_adapter,
        manifest_note="Preop ParaView visualization submitted",
    )


def submit_postop_paraview_viz(
    *,
    workspace_root: str | Path,
    run_id: str,
    cycle_duration_s: float,
    transfer_adapter: FileTransferAdapter | None = None,
    scheduler_adapter: SchedulerAdapter | None = None,
    remote_exec_adapter: RemoteExecAdapter | None = None,
) -> ParaViewVizSubmissionResult:
    root = detect_workspace_root(workspace_root)
    validated_run_id = validate_run_id(run_id)
    local_run = build_local_run_paths(root, validated_run_id)
    manifest = read_manifest(local_run.manifest)
    config = load_workspace_config(root)
    cluster = resolve_cluster(config, str(manifest.cluster.get("name")))
    prepared = _prepare_postop_paraview_viz_job(
        workspace_root=root,
        run_id=validated_run_id,
        manifest=manifest,
        cluster=cluster,
    )
    return _submit_prepared_paraview_viz_job(
        prepared=prepared,
        manifest_path=local_run.manifest,
        cluster=cluster,
        config=config,
        transfer_adapter=transfer_adapter,
        scheduler_adapter=scheduler_adapter,
        remote_exec_adapter=remote_exec_adapter,
        manifest_note="Postop ParaView visualization submitted",
    )


def submit_adaptation_paraview_viz(
    *,
    workspace_root: str | Path,
    run_id: str,
    model: str,
    transfer_adapter: FileTransferAdapter | None = None,
    scheduler_adapter: SchedulerAdapter | None = None,
    remote_exec_adapter: RemoteExecAdapter | None = None,
) -> ParaViewVizSubmissionResult:
    root = detect_workspace_root(workspace_root)
    validated_run_id = validate_run_id(run_id)
    local_run = build_local_run_paths(root, validated_run_id)
    manifest = read_manifest(local_run.manifest)
    config = load_workspace_config(root)
    cluster = resolve_cluster(config, str(manifest.cluster.get("name")))
    prepared = _prepare_adaptation_paraview_viz_job(
        workspace_root=root,
        run_id=validated_run_id,
        manifest=manifest,
        cluster=cluster,
        model=model,
    )
    return _submit_prepared_paraview_viz_job(
        prepared=prepared,
        manifest_path=local_run.manifest,
        cluster=cluster,
        config=config,
        transfer_adapter=transfer_adapter,
        scheduler_adapter=scheduler_adapter,
        remote_exec_adapter=remote_exec_adapter,
        manifest_note=f"Adaptation {model.upper()} ParaView visualization submitted",
    )
